version: "3.8"

services:
  # Traefik 2 - Reverse Proxy
  app:
    image: traefik
    container_name: DO__traefik
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/rules:/rules
      - ./config/traefik/acme:/acme
      - ./config/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./config/traefik/users:/etc/traefik/users
      - ./config/traefik/certs:/etc/certs:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.local_traefik.rule=Host(`traefik.lan`)
      - traefik.http.services.local_traefik.loadbalancer.server.port=8080
      - traefik.http.routers.local_traefik.entrypoints=websecure
      - traefik.http.routers.local_traefik.tls=true
    networks:
      - default

networks:
  default:
    driver: bridge
    name: traefik
